# Generated by Django 6.0.1 on 2026-01-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Remote', 'Remote')], max_length=20)),
                ('experience', models.PositiveIntegerField()),
                ('salary', models.PositiveIntegerField()),
                ('skills', models.TextField()),
                ('is_remote', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
