# signup
###
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
    "username" : "user",
    "email" : "user@gmail.com",
    "password" : "Password@123"
}

# Add employee
###
POST http://127.0.0.1:8000/Employee/
Content-Type: application/json
Authorization: Basic user:Password@123

{
    "name": "Rahul Kumar",
    "department": "IT",
    "designation": "Backend Developer",
    "salary": 45000,
    "email": "rahul@gmail.com",
    "date_of_joining": "2023-06-15"
}
# List Employee
###
GET http://127.0.0.1:8000/Employee/
Accept: application/json
Authorization: Basic user:Password@123

#Retrieve
###
GET http://127.0.0.1:8000/Employee/3/
Accept : application/json
Authorization: Basic user:Password@123

#update 
###
PUT http://127.0.0.1:8000/Employee/3/
Content-Type: application/json
Authorization: Basic user:Password@123

{
 "id": 3,
 "title": "updated bike fuel",
 "category": "fuel",
 "amount": 2500.0,
 "created_at": "2026-02-03T16:04:31.473919Z",
 "owner": 1
}


#delete
###
DELETE  http://127.0.0.1:8000/Employee/2/
Authorization: Basic user:Password@123
