# Generated by Django 6.0.2 on 2026-03-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizNest', '0002_quiz_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='user',
            new_name='owner',
        ),
    ]
