# Generated by Django 6.0.2 on 2026-03-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizNest', '0003_rename_user_quizattempt_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='owner',
            new_name='created_by',
        ),
    ]
