# Generated by Django 5.2.7 on 2026-02-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryHub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
