# Generated by Django 5.2.7 on 2026-02-19 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryHub_app', '0002_query_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='QueryHub_app.query'),
        ),
    ]
