# signup

POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
    "username": "rahul",
    "password": "Password@123",
    "email": "rahul@gmail.com",
    "phone": "9345678123"
}

# api call for token
###
POST http://127.0.0.1:8000/token/
Content-Type: application/json

{
    "username":"rahul",
    "password":"Password@123"
}


# api call for creating query
###
POST http://127.0.0.1:8000/query/
Content-Type: application/json
Authorization: Token 8680dc9da4c6362e7a8dce0f1f79c3eaae3cef97

{
    "question" : "2024 ipl winner"
}

# list all queries
###
GET http://127.0.0.1:8000/query/
Authorization: Token 8680dc9da4c6362e7a8dce0f1f79c3eaae3cef97
Accept: application/json

# api call for creating a solution
###
POST http://127.0.0.1:8000/query/3/add-answer/
Content-Type: application/json
Authorization: Token c9d85dbbcf30f19d4f3da3e61b93437bfd4ff28b

{
    "answer" : "fourteen"
}

# api call for retrieving a query
###
GET http://127.0.0.1:8000/query/2/
Authorization: Token 8680dc9da4c6362e7a8dce0f1f79c3eaae3cef97
Accept: application/json

# delete 
###
DELETE http://127.0.0.1:8000/query/4/delete/
Authorization: Token 8680dc9da4c6362e7a8dce0f1f79c3eaae3cef97
Accept: application/json

# upvote
###
POST http://127.0.0.1:8000/query/1/vote/
Authorization: Token f62cedbf1796132fdd0bed6784f8f30bf7537674



