# Generated by Django 5.2.7 on 2026-02-02 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('fule_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Disel'), ('ev', 'Ev')], default='petrol', max_length=100)),
                ('owner_condition', models.PositiveIntegerField()),
                ('color', models.CharField()),
                ('price', models.PositiveIntegerField()),
                ('running_km', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
