# Generated by Django 6.0.1 on 2026-02-03 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('food', 'Food'), ('groceries', 'Groceries'), ('rent', 'Rent'), ('transport', 'Transportation'), ('fuel', 'Fuel'), ('shopping', 'Shopping'), ('medical', 'Medical'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('travel', 'Travel'), ('bills', 'Bills'), ('investment', 'Investment'), ('gift', 'Gifts'), ('others', 'Others')], default='food', max_length=100)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
