# Generated by Django 6.0.2 on 2026-02-24 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=200)),
                ('activity_level', models.CharField(choices=[('1.2', 'Sedentary (little/no exercise)'), ('1.375', 'Lightly active (exercise 1-3 days/week)'), ('1.55', 'Moderately active (exercise 3-5 days/week)'), ('1.725', 'Very active (exercise 6-7 days/week)'), ('1.9', 'Extra active (very intense activity)')], default='1.2', max_length=200)),
                ('bmr', models.FloatField(null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
