# signup
###
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
    "username" : "user1",
    "email" : "user1@gmail.com",
    "password" : "Password@123"
}

# Add expense
###
POST http://127.0.0.1:8000/expense/
Content-Type: application/json
Authorization: Token 8e0a0c9e42b4f4eead2530a5c7a2a3d9f87707c1

{
    "title" : "Tea",
    "amount": 20,
    "category" : "food"
}

# List expense
###
GET http://127.0.0.1:8000/expense/
Accept: application/json
Authorization: Token 8e0a0c9e42b4f4eead2530a5c7a2a3d9f87707c1

#Retrieve
###
GET http://127.0.0.1:8000/expense/3/
Accept : application/json
Authorization: Token 8e0a0c9e42b4f4eead2530a5c7a2a3d9f87707c1

#update 
###
PUT http://127.0.0.1:8000/expense/3/
Content-Type: application/json
Authorization: Token 8e0a0c9e42b4f4eead2530a5c7a2a3d9f87707c1

{
 "id": 3,
 "title": "updated bike fuel",
 "category": "fuel",
 "amount": 2500.0,
 "created_at": "2026-02-03T16:04:31.473919Z",
 "owner": 1
}


#delete
###
DELETE  http://127.0.0.1:8000/expense/2/
Authorization: Token 8e0a0c9e42b4f4eead2530a5c7a2a3d9f87707c1

#summary
###
GET http://127.0.0.1:8000/summary/
Accept: application/json
Authorization: Token 8e0a0c9e42b4f4eead2530a5c7a2a3d9f87707c1

#token authentication
###
POST http://127.0.0.1:8000/auth/
Content-Type: application/json

{
    "username" : "",
    "password" : "Password@123"
}