# Generated by Django 5.2.7 on 2026-01-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids')], default='kids', max_length=20)),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='small', max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
