# Generated by Django 5.2.7 on 2026-02-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0002_alter_user_id_poll_choice_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('owner', 'poll_object')},
        ),
    ]
