# api call for create clothing
POST http://127.0.0.1:8000/clothing/
Content-Type: application/json
Authorization: Basic cloth_user:password@123

{
    "name": "Cotton Shorts",
    "brand": "Puma",
    "category": "kids",
    "size": "small",
    "color": "Red",
    "price": 499,
    "stock": 40
}





# api call for list clothing
###
GET http://127.0.0.1:8000/clothing/
Accept: application/json
Authorization: Basic cloth_user:password@123



# api call for retrieve clothing
###
GET http://127.0.0.1:8000/clothing/2/
Accept: application/json
Authorization: Basic cloth_user:password@123



# api call for update clothing
###
PUT http://127.0.0.1:8000/clothing/2/
Content-Type: application/json
Authorization: Basic cloth_user:password@123

{
    "id": 2,
    "name": "Denim Jacket",
    "brand": "Levis",
    "category": "women",
    "size": "large",
    "color": "Blue",
    "price": 2499,
    "stock": 16
}



# api call for delete clothing
###
DELETE http://127.0.0.1:8000/clothing/3/
Authorization: Basic cloth_user:password@123


### 
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{
  "username" :"cloth_user",
  "first_name":"u",
  "last_name":"s",
  "email" : "user@gmail.com",
  "password" : "password@123"
}